databases:
  - name: boardgamewinner
    databaseName: boardgamewinner
    user: boardgamewinner

services:
  - type: web
    name: boardgamewinner
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: boardgamewinner
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false